#!/bin/bash
#How to install USB in Virtualbox

cat << _EOF_
<html>
<head>
	<title>
	How to Install USB in VirtualBox
	</title>
</head>

<body>
1. Download and Install virtualbox extension Pack on windows.
2. After installing, reboot the host OS for changes to take effect.
3. Under settings in virtualNox 'go to' USB and click on add USB selecting the right version of your USB model.
4. Once Virtual Box OS starts, plug in the USB and it will appear.
</body>
</html>
_EOF_
